version: '3.8'

services:
  web:
    build: .
    command: python /it-software/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/it-software
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - software_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  software_data: