# Generated by Django 3.2.14 on 2022-08-07 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0003_auto_20220807_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email_license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.emaillicense', verbose_name='Email License')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.jobposition', verbose_name='Job Position')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.location', verbose_name='Location')),
            ],
        ),
    ]
