# Generated by Django 3.2.14 on 2022-08-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLicense',
            fields=[
                ('license_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='License ID')),
                ('license_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='License Type')),
            ],
        ),
    ]
