# Generated by Django 3.2.14 on 2022-08-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_emaillicense'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=255, verbose_name='Position Name')),
            ],
        ),
        migrations.AlterField(
            model_name='emaillicense',
            name='license_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='License Price'),
        ),
    ]
