from django.urls import path

from setup.models import Location
from .views import (
    LocationListView,
    LocationCreateView,
    LocationUpdateView,
    LocationDeleteView,
    LocationDetailView,
    EmailLicenseListView,
    EmailLicenseCreateView,
    EmailLicenseUpdateView,
    EmailLicenseDetailView,
    EmailLicenseDeleteView,
    JobPositionListView,
    JobPositionCreateView,
    JobPositionUpdateView,
    JobPositionDetailView,
    JobPositionDeleteView,
)

app_name = "setup"

urlpatterns = [
    path(
        "positions/<pk>/delete/",
        JobPositionDeleteView.as_view(),
        name="job_position_delete",
    ),
    path(
        "locations/<pk>/delete/",
        LocationDeleteView.as_view(),
        name="location_delete",
    ),
    path(
        "licenses/<pk>/delete/",
        EmailLicenseDeleteView.as_view(),
        name="email_license_delete",
    ),
    path(
        "positions/<pk>/edit/",
        JobPositionUpdateView.as_view(),
        name="job_position_edit",
    ),
    path(
        "locations/<pk>/edit/",
        LocationUpdateView.as_view(),
        name="location_edit",
    ),
    path(
        "licenses/<pk>/edit/",
        EmailLicenseUpdateView.as_view(),
        name="email_license_edit",
    ),
    path(
        "positions/add/",
        JobPositionCreateView.as_view(),
        name="job_position_add",
    ),
    path(
        "licenses/add/",
        EmailLicenseCreateView.as_view(),
        name="email_license_add",
    ),
    path(
        "locations/add/",
        LocationCreateView.as_view(),
        name="location_add",
    ),
    path(
        "positions/<pk>/",
        JobPositionDetailView.as_view(),
        name="job_position_detail",
    ),
    path(
        "licenses/<pk>/",
        EmailLicenseDetailView.as_view(),
        name="email_license_detail",
    ),
    path(
        "locations/<pk>/",
        LocationDetailView.as_view(),
        name="location_detail",
    ),
    path(
        "positions/",
        JobPositionListView.as_view(),
        name="job_position_list",
    ),
    path(
        "licenses/",
        EmailLicenseListView.as_view(),
        name="email_license_list",
    ),
    path(
        "locations/",
        LocationListView.as_view(),
        name="location_list",
    ),
]
